<html>

<body style="background-color : black">

</body>
<script>
    //CALLBACK HELL (Many Dependent async tasks)
    /*function bookVenue (callback){
        setTimeout(function(){
            console.log('Venue Booked')
            callback()
        },1000)
    }
    function orderCake (callback){
        setTimeout(function(){
            console.log('Cake Ordered')
            //callback() Inversion of control problem here because function is not called back
        },1000)
    }
    function sendInvites (callback){
        setTimeout(function(){
            console.log('Invitations Send')
        },1000)
        callback()
    }
    function buyDecoration (callback){
        setTimeout(function(){
            console.log('Decoration Purchased')
            callback()
        },1000)
    }
    function setupVenue (callback){
        setTimeout(function(){
            console.log('Venue Setted Up')
            callback()
        },1000)
    }


    bookVenue(function(){
        orderCake(function(){
            sendInvites(function(){
                buyDecoration(function(){
                    setupVenue(function(){
                        console.log('Party Ready')
                    })
                })
            })
        })
    })
    */

    //Problems of Callback HELL - Hard Readablity & Inversion of control(Kisi or pe trust karna ki vo hamare diye hue function ko call karega)
    //Solutions to avoid callback hell - promises
    
    //Promise is an object which represents the eventual completion or failure of an async operation.
    //To handle promises - .then()&.catch() / async-await
    
    //PROMISE CHAINING
    //Promise chaining means that each .then() waits for the Promise returned by the previous .then() to resolve.
    //If any .then() returns a rejected Promise or throws an error, the .catch() is triggered, and all .then()s after that are skipped.
    //If the catch handler throws an error, the Promise chain will return a rejected promise with that error.
    function bookVenue (){
        return new Promise(function(resolve, reject){
            setTimeout(function(){
                console.log('Venue Booked')
                resolve()
            },1000)
        })
    }
    function orderCake (){
        return new Promise(function(resolve, reject){
            setTimeout(function(){
                console.log('Cake Ordered')
                resolve()
            },1000)
        })
    }
    function sendInvites (){
        return new Promise(function(resolve, reject){
            setTimeout(function(){
                console.log('Invitations Send')
                resolve()
            },1000)
        })
    }
    function buyDecoration (){
        return new Promise(function(resolve, reject){
            setTimeout(function(){
                console.log('Decoration Purchased')
                resolve()
            },1000)
        })
    }
    function setupVenue (){
        return new Promise(function(resolve, reject){
            setTimeout(function(){
                console.log('Venue Setted Up')
                resolve()
            },1000)
        })
    }

    //using promises
    // bookVenue()
    // .then(orderCake)
    // .then(sendInvites)
    // .then(buyDecoration)
    // .then(setupVenue)
    // .then(() => console.log('Party Ready'))

    //using async-await
    async function arrangeParty(){
        await bookVenue()
        await orderCake()
        await sendInvites()
        await buyDecoration()
        await setupVenue()
        console.log('Party Ready')
    }
    arrangeParty()

    //async-await are used to handle the promises just like then and catch.
    //async means a function will always returns a promise
    //await suspends the function execution and waits for the promise to be settled.
    //If the promise is resolved then the value is returned
    //If the promise is rejected then the error is thrown which needs to be handled by using try-catch.
    //If the return value is not promise, then Js automatically wraps that return value into a resolved promise
    //If the error is thrown in the catch block or the error thrown is not handled, then the async function automatically returns a rejected promise.
    
    //⚠️ Common Misconception
    //Some people think await pauses the whole program. That’s wrong.
    //✅ It only pauses the current async function, not the entire JS engine or UI.

    //fetch()
    //It is a function which returns a promise.
    //The returned promise is then handled by then or catch
    //It has high priority(priority queue) than any other async operation
    //It only rejects the promise if there is network issue(means the request is not able to reach server)
    //For errors like 404(Page not found), we need to manually check the response.ok property or response.status
</script>

</html>
